exports.error = () => 'function() {throw new Error("Error!")}';
exports.Datenowunix = () => 'function() {return (new Date()).getTime() / 1000 | 0;}';
exports.Datenowfloat = () => 'function() {return (new Date()).getTime() / 1000;}';
exports.Performancenow = () => '(function() {return performance.now.bind(performance) || function() {return (new Date()).getTime();};}())';
exports.Consolelogint = exports.Consolelogfloat = exports.Consolelogstr = () => 'console.log.bind(console)';
exports.Consolelogbool = () => 'function(x) {console.log(x ? \'true\' : \'false\')}';
exports.getNaN = () => 'function() {return NaN;}';
exports.getNegZero = () => 'function() {return -0.0;}';
exports.getInfinity = () => 'function() {return Infinity;}';
exports.getNegInfinity = () => 'function() {return -Infinity;}';
exports.featureArcTrig = () => 'function() {return true;}';
